<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bc_voting"
 *
 * Auto generated by Extension Builder 2015-10-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'bc_voting',
	'description' => 'Online voting plattform based on blockchain technologies',
	'category' => 'plugin',
	'author' => 'Louis Göttertz',
	'author_email' => 'info2016@goettertz.de',
	'dependencies' => 'extbase,fluid',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
<<<<<<< HEAD
	'version' => '0.8.132',
=======
	'version' => '0.8.131',
>>>>>>> d75d16d8fca1a4894b963dab23e2a035cf2526db
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
?>
